### PR TITLE
Add functions to modify text properties

### LINKED ISSUE #2: Create function to easily modify the fontSize, fontWeight and lineHeight properties of the text
In the typescript file(Paginate.ts), there are variables to specify the line height, font weight, and font size. It would be nice if a function is created to update these values.

This function should serve as an api to modify these values apart from the the assignment that happens in on initialization.

Also, inputs can be added to the  current html to utilize this api.

Goodluck 👍💪

### PR DESCRIPTION
**Pull request by sushma1031**
Fixes #2 

Demo:

https://github.com/Cedar-81/paginate/assets/123486589/3aa8689b-3ec6-4134-939d-cb55657569a5

### CODE REVIEW

**Comment by Cedar-81** [comment]
Hey, just checked out ur code... It looks fine but it seems you didn't run tsc after modifying the typescript file cause the javascript file in the dist folder currently doesn't have your changes.

Please fix that.

Thanks for the good work 💪

**Comment by sushma1031** [comment]
Oh, right, sure, I'll do that.

**Comment by sushma1031** [comment]
> Hey, just checked out ur code... It looks fine but it seems you didn't run tsc after modifying the typescript file cause the javascript file in the dist folder currently doesn't have your changes.

Since the code has been refactored and the dist folder is no longer part of the code, do I still need to make this change?

**Comment by sushma1031** [comment]
@Cedar-81 I updated the styles to match the current colours, let me know if it's all right

Screenshot (149)

**Pull request closed without merging**
